#!/usr/bin/env bash
#
# Build a throwaway folder of fake videos and subtitles for trying the TUI by hand.
#
# The files carry realistic names and a few bytes of placeholder content; nothing
# here is a playable video. Every scenario the preview can report is represented,
# so the whole workflow — preview, tick, strict, subfolders, match level, apply —
# can be exercised against one folder.
#
# Usage: scripts/make-demo-library.sh [target-directory]   (default: ./demo-library)
#
# Renaming mutates the library, so re-run this to get a clean slate. Only a
# directory this script created before (it leaves a .demo-library marker) or a
# path that does not exist yet is ever written to.

set -euo pipefail

target=${1:-demo-library}
marker=$target/.demo-library

if [[ -e $target ]]; then
    if [[ ! -f $marker ]]; then
        echo "refusing to touch '$target': not a generated demo library" >&2
        echo "(delete it yourself, or pass a different path)" >&2
        exit 1
    fi
    rm -rf "$target"
fi

# A fake video: enough bytes that a file browser shows a size, no real container.
video() {
    mkdir -p "$(dirname "$target/$1")"
    printf 'placeholder video: %s\n' "$(basename "$1")" >"$target/$1"
}

# A fake subtitle, in whichever of the two formats the extension asks for.
subtitle() {
    local path=$1 name
    name=$(basename "$path")
    mkdir -p "$(dirname "$target/$path")"
    case $path in
    *.ass | *.ssa)
        cat >"$target/$path" <<EOF
[Script Info]
Title: $name

[Events]
Format: Layer, Start, End, Style, Text
Dialogue: 0,0:00:01.00,0:00:04.00,Default,placeholder subtitle
EOF
        ;;
    *)
        cat >"$target/$path" <<EOF
1
00:00:01,000 --> 00:00:04,000
placeholder subtitle: $name
EOF
        ;;
    esac
}

mkdir -p "$target"
printf 'Generated by scripts/make-demo-library.sh. Safe to delete.\n' >"$marker"

# Top level: one plain pair, so a preview with subfolders off is not empty.
video 'Midnight.Broadcast.S01E01.1080p.WEB-DL.x265-GRP.mkv'
subtitle 'Midnight Broadcast - S01E01 [chs].ass'

# Episode ids matched across two different release namings, plus the two
# everyday reasons a subtitle drops out: no such episode, and already named.
video 'Nebula Archive S01/Nebula.Archive.S01E01.1080p.WEB-DL.x265-RARBG.mkv'
video 'Nebula Archive S01/Nebula.Archive.S01E02.1080p.WEB-DL.x265-RARBG.mkv'
video 'Nebula Archive S01/Nebula.Archive.S01E03.1080p.WEB-DL.x265-RARBG.mkv'
subtitle 'Nebula Archive S01/[Fansub] Nebula Archive - S01E01 [chs].ass'
subtitle 'Nebula Archive S01/[Fansub] Nebula Archive - S01E02 [chs].ass'
subtitle 'Nebula Archive S01/[Fansub] Nebula Archive - S01E02 [eng].srt'
subtitle 'Nebula Archive S01/[Fansub] Nebula Archive - S01E07 [chs].ass'
subtitle 'Nebula Archive S01/Nebula.Archive.S01E03.1080p.WEB-DL.x265-RARBG.ass'

# No episode ids anywhere, so these lean on the fuzzy matcher. The three pairs
# are deliberately loosening: one holds at every level, one drops at cautious,
# one needs relaxed, and the last never matches at all.
video 'Features/The.Quiet.Harbor.2019.1080p.BluRay.x264-GRP.mkv'
video 'Features/Drifting.Lanterns.2021.720p.WEBRip.x264.mp4'
video 'Features/Paper.Kite.Symphony.2018.1080p.BluRay.x264.mkv'
subtitle 'Features/The Quiet Harbor 2019.srt'
subtitle 'Features/Drifting Lantern 2021 Restored CHT.ass'
subtitle 'Features/Paper Kites Symphony fansub reencode v2.ass'
subtitle 'Features/Conference Panel Recording.vtt'

# Target names already taken, and one episode id claimed by two videos.
video 'Solar Winds S02/Solar.Winds.S02E05.mkv'
video 'Solar Winds S02/Solar.Winds.S02E06.PROPER.mkv'
video 'Solar Winds S02/Solar.Winds.S02E06.REPACK.mkv'
subtitle 'Solar Winds S02/Solar.Winds.S02E05.ass'
subtitle 'Solar Winds S02/Solar Winds - S02E05 [eng].ass'
subtitle 'Solar Winds S02/Solar Winds - S02E06 [chs].ass'

# CJK names, composed and with a bracketed group the matcher has to strip.
video '星际档案 第一季/星际档案.S01E01.1080p.mkv'
video '星际档案 第一季/星际档案.S01E02.1080p.mkv'
subtitle '星际档案 第一季/[樱花字幕组] 星际档案 S01E01 [简体].ass'
subtitle '星际档案 第一季/[樱花字幕组] 星际档案 S01E02 [简体].ass'

# Subtitles with no video beside them at all.
subtitle 'Loose Subtitles/Orphan.Show.S01E01.chs.srt'
subtitle 'Loose Subtitles/Orphan.Show.S01E02.chs.srt'

cat <<EOF
Demo library ready: $target

Try it:
  cargo run -- --tui $target      # then turn on "include subfolders" and press p

What each folder is there to show:
  (top level)          one plain match, so a non-recursive preview is not empty
  Nebula Archive S01/  episode-id matches, a missing episode, an already-named file
  Features/            fuzzy matches at three strengths; step the match level and
                       watch "Drifting Lantern" and "Paper Kites" come and go
  Solar Winds S02/     a taken target name (flip strict on and off), an ambiguous episode
  星际档案 第一季/     CJK names with a fansub group to strip
  Loose Subtitles/     subtitles with no video in the folder

Re-run this script to undo an apply and start over. Remove it with:
  rm -rf $target
EOF
